name: auth_nav
description: Library support navgiation for authorization flow on flutter.
version: 2.1.0
homepage: https://github.com/dangngocduc/auth_nav
repository: https://github.com/dangngocduc/auth_nav
issue_tracker: https://github.com/dangngocduc/auth_nav/issues
documentation: https://github.com/dangngocduc/auth_nav
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
